# Site settings
title: Title of this page
author: Author_name
name: Giuseppe
email: your-email@domain.com
description: "Test website to try Jekyll on GH-Pages."
twitter_username: twitter_name 
linkedin_username: giuseppe-corrado-6563a812b
# github_username: 

# Build settings
remote_theme: jekyll/minima
